# Generated by Django 3.1 on 2020-08-30 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ('-fecha_salida',)},
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='link',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='texto',
        ),
        migrations.AddField(
            model_name='trailer',
            name='duracion',
            field=models.CharField(default='0:00', max_length=10),
        ),
        migrations.AddField(
            model_name='trailer',
            name='fecha_salida',
            field=models.DateField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='link_imagen',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='link_video',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='vistas',
            field=models.PositiveIntegerField(auto_created=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
