# Generated by Django 3.1 on 2020-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200830_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='vistas',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
