# Generated by Django 3.1 on 2020-08-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200830_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='dislikes',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='likes',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
