# Generated by Django 3.1 on 2020-08-30 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_auto_20200830_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('reaccion', models.ImageField(upload_to='')),
                ('trailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.trailer')),
                ('usuario_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('trailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.trailer')),
                ('usuario_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
