# Generated by Django 3.1 on 2020-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_comentario_reaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default='', max_length=500),
        ),
    ]
