# Generated by Django 3.1 on 2020-08-30 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0006_comentario_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('fecha', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('trailer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.trailer')),
                ('usuario_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
